"""Minimal environment contract required by the protocol-driven runtime.

This is intentionally smaller than Alpha 3 Environment Fabric. Its purpose is
only to keep the execution engine domain-neutral while the richer Environment
Adapter SPI (provisioning, composite snapshots, virtual clocks, resources,
fault providers) is developed separately.
"""

from __future__ import annotations

from typing import Any, Protocol


class RuntimeEnvironment(Protocol):
    """Evaluator-owned environment capabilities used by ReferenceRuntime."""

    logical_time: int

    def reset(self) -> None: ...
    def public_observation(self) -> dict[str, Any]: ...
    def privileged_projection(self, name: str) -> Any: ...
    def state_digest(self) -> str: ...
    def snapshot_state(self) -> dict[str, Any]: ...
    def restore_state(self, state: dict[str, Any], logical_time: int) -> None: ...
    def call_tool(self, name: str, arguments: dict[str, Any]) -> tuple[Any, dict[str, Any], dict[str, Any]]: ...
    def semantic_diff(self, before: dict[str, Any], after: dict[str, Any]) -> list[dict[str, Any]]: ...
